name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Clone BotFather
        run: |
          git clone https://github.com/python-telegram-bot/python-telegram-bot --recursive


      - name: install BotFather
        run: |
          cd python-telegram-bot
          sudo pip setup.py install
