on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.actor }}/bot:latest
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: student
          key: ${{ secrets.SSH }}
          script: |
            !cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
            chmod 700 ~/.ssh/authorized_keys
            echo ${{ secrets.GHCR_PASSWORD }} | docker login --username ${{ github.actor }} --password-stdin ghcr.io
            docker run --rm --detach ghcr.io/${{ github.actor }}/bot:latest
